name: JSON Linter

on:
  push:
    branches:
      - main

jobs:
  json_linter_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checkout the repository to access the files

      - name: Install JSON Linter
        run: |
          npm install -g @prantlf/jsonlint  # Install the jsonlint package globally

      - name: Run JSON Linter
        run: |
          jsonlint $GITHUB_WORKSPACE/JSON_DetailedDataSchema_Example.json  # Lint the DataSchema.json file (replace with your actual JSON file)
